import { ReactNode } from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/context/Providers";
import { Toaster } from "sonner";
import { auth } from "@/auth.config";
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {

  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          {/* Header */}
          <Navbar />
          <main>
          {children}
          </main>
          <Toaster richColors />
        </body>
      </html>
    </Providers>
  );
}
